import {useState,useRef} from 'react';
import {Download,Upload,FileText,CheckCircle2,X} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {type Entry} from './map-config';
import {downloadText,portableHtml,snapshot,validateSnapshot,type Snapshot} from './local-progress';
type Props={open:boolean;onClose:()=>void;entries:Record<string,Entry>;onImport:(data:Snapshot)=>void;documentUrl:string};
export default function OfflineFiles({open,onClose,entries,onImport,documentUrl}:Props){
 const [staged,setStaged]=useState<Snapshot|null>(null),[message,setMessage]=useState(''),[problem,setProblem]=useState('');
 const input=useRef<HTMLInputElement>(null);
 const stamp=()=>new Date().toISOString().slice(0,10);
 function exportFile(html:boolean){try{const data=snapshot(entries);downloadText(html?portableHtml(data):JSON.stringify(data,null,2),`C_CPP_Roadmap_${stamp()}.${html?'html':'json'}`,html?'text/html;charset=utf-8':'application/json;charset=utf-8');setMessage(html?'Копия HTML подготовлена к скачиванию. В ней уже есть твой прогресс.':'Резервный JSON подготовлен к скачиванию.');setProblem('')}catch(e){setProblem((e as Error).message)}}
 async function readFile(file?:File){if(!file)return;setProblem('');setMessage('');setStaged(null);try{if(file.size>5*1024*1024)throw Error('Файл слишком большой: максимум 5 МБ.');setStaged(validateSnapshot(JSON.parse(await file.text())))}catch(e){setProblem((e as Error).message||'Не удалось прочитать файл.')}finally{if(input.current)input.current.value=''}}
 return <Sheet open={open} onOpenChange={v=>{if(!v)onClose()}}><SheetContent className="detail-panel" showCloseButton={false}><SheetHeader className="detail-header"><div className="detail-overline"><span className="module-tag">АВТОНОМНАЯ ВЕРСИЯ</span><button className="icon-button" onClick={onClose} aria-label="Закрыть мои файлы"><X size={20}/></button></div><SheetTitle className="detail-title">Мои файлы и прогресс</SheetTitle><SheetDescription className="detail-goal">Карта работает без аккаунта и сервера. Файлы с отметками и заметками остаются у тебя.</SheetDescription></SheetHeader><div className="detail-content offline-files"><div className="offline-tip"><b>После занятия — сохрани копию</b><p>Отметки автоматически сохраняются в этом браузере. Очистка его данных, другой браузер или перенос HTML могут сбросить локальную копию. Надёжная резервная копия — скачанный HTML или JSON.</p></div><button className="offline-action primary" onClick={()=>exportFile(true)}><Download size={21}/><span><b>Скачать HTML с прогрессом</b><small>Карта, темы, материалы и твои отметки в одном файле</small></span></button><button className="offline-action" onClick={()=>exportFile(false)}><Download size={21}/><span><b>Экспорт прогресса в JSON</b><small>Небольшой файл для резервной копии и переноса</small></span></button><button className="offline-action" onClick={()=>input.current?.click()}><Upload size={21}/><span><b>Импорт прогресса из JSON</b><small>Выбрать ранее сохранённый файл</small></span></button><input ref={input} type="file" accept=".json,application/json" onChange={e=>void readFile(e.target.files?.[0])} className="offline-hidden" aria-label="Файл прогресса JSON"/>{staged&&<div className="offline-import"><b>В файле {staged.entries.length} записей</b><p>Объединить с текущими данными. Если одна тема есть в обеих копиях, останется запись с более поздним временем изменения. Остальные темы сохранятся.</p><button className="primary-button" onClick={()=>{onImport(staged);setStaged(null);setMessage('Прогресс импортирован.');setProblem('')}}>Объединить прогресс</button><button className="offline-cancel" onClick={()=>setStaged(null)}>Отмена</button></div>}{message&&<p className="offline-success" role="status"><CheckCircle2 size={18}/>{message}</p>}{problem&&<p className="offline-problem" role="alert">{problem}</p>}<div className="offline-note"><b>Для другого компьютера</b><p>Открой там скачанный HTML с прогрессом. Либо открой чистую карту и импортируй свой JSON. Автоматической синхронизации между устройствами нет.</p><b>Материалы</b><p>Сама карта полностью офлайн. Интернет нужен только при переходе по внешним ссылкам на книги и документацию.</p><a href={documentUrl} download="C_CPP_roadmap.docx"><FileText size={16}/>Скачать исходный документ</a></div></div></SheetContent></Sheet>;
}
